#!/bin/dash
# legit-init
# Nan Wu
# 7/7/19
# This is the init command that can create an
# empty legit repository


# when directory is exist, echo error
if [ -e .legit ]
then
    echo "legit-init: error: .legit already exists"
else

# when directory is not exist, create one
	mkdir .legit
    echo "Initialized empty legit repository in .legit"
fi
